# Hexo Configuration
## Docs: http://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 晋哥哥的私房钱
subtitle: 
description: 
author: Bill Zhang
language: zh-CN
timezone: 

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://jingege.me
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render: 404.html

# Writing
new_post_name: :year-:month-:day-:title.md #:title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: true
  tab_replace:

# Category & Tag
default_category: 随笔
category_map:
  技术: technology
  生活: life
  随笔: note
  我的故事: story
tag_map:
  信息安全: information-security
  软件工程: software-engineering
  PHP: php
  C++: cpp
  开源: opensource
  Java: java
  Ant: ant
  Clojure: clojure
  DataX: datax
  Emacs: emacs
  Hash: hash
  Hive: hive
  iOS: ios
  Leiningen: leiningen
  Linux: linux
  ObjC: objc
  Oozie: oozie
  Yaserde: yaserde
  Golang: golang
  HTML: html
  Linux: linux
  Node.js: nodejs
  计划: plans
  技术: technology
  计算机网络: network
  互联网: internet
  笔记: reading-notes
  价值观: values
  教程: tutorials
  读书: reading
  总结: summary
  教育: education
  作品: works
  随笔: note
  单元测试: unit-test
  生活: life
  互联网资讯: news
  购物: shopping
  生活记录: live
  物理: physical
  MongoDB: mongodb
  计算机科学: computer-science
  电影: movie
  博客: blog
  学校考试: exam
  黑客: hacker
  比特币: bitcoin
  冷知识: cold-knowledge
  SICP: sicp

tag_generator:
  per_page: 10

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY M 月 D 日
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 3
pagination_dir: page

# Extensions
## Plugins: http://hexo.io/plugins/
## Themes: http://hexo.io/themes/
theme: simpleblock

# Deployment
## Docs: http://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: https://github.com/jingege/jingege.github.com.git
  branch: master
  message: New post

feed:
  type: atom
  path: atom.xml
  limit: 100
